### ISSUE TITLE
STAT and fvar issues

### ISSUE THREAD

**Issue by thlinard** [coreyhu/Urbanist#20]
In `STAT`:

- Double Black instances.
- Regular instance should be elidable.
- Italic instances are missing (two instances: Roman, elided, and Italic).

In `fvar` and `name`:

- `postscriptNameID` should have a `nameID 25` component.

`gftools gen-stat` could solve these issues.

**Comment by coreyhu** [comment]
Thanks for the feedback! I just merged #21, which should fix these issues. Please let me know if anything is off!

**Comment by thlinard** [comment]
Hi @coreyhu 

- In `STAT`, the Regular and Roman instances are missing (they must be present, but elidable).
- The `postscriptNameID` is incomplete.

I made a corrected version with `ttx`, if you want to take a look.
[Urbanist-Variable.ttf.zip](https://github.com/coreyhu/Urbanist/files/6500708/Urbanist-Variable.ttf.zip)

Anyway, since you have submitted your typeface to add it to Google Fonts, maybe you should use `gftools builder` + a `config.yaml` file (the one in https://github.com/Omnibus-Type/Texturina/blob/master/sources/config.yaml is a good example).

**Comment by coreyhu** [comment]
Just setup `gftools builder` and it's a lifesaver! I'll add it to the export pipeline in the future.  

I think I understand what you mean by the missing Roman and Regular instances and it should be fixed in this version:
[Urbanist[ital,wght].ttf](https://github.com/coreyhu/Urbanist/raw/gftool_builder/fonts/variable/Urbanist%5Bital%2Cwght%5D.ttf)

From what I can tell, the issue with the improper `postscriptNameID` should be fixed as well. Are you able to confirm?

**Comment by thlinard** [comment]
Hi @coreyhu

Very good! All issues fixed! You can test the result in [Samsa](https://www.axis-praxis.org/samsa/). Don't forget to put your `config.yaml` in the source, the person from the Google Fonts team who onboard your font will appreciate. 😀

Still, your `ital` axis is more of a `slnt` axis, but the support is complicated (https://github.com/googlefonts/gftools/issues/295), so it might stay this way, I don't know.

**Comment by coreyhu** [comment]
Thanks for your help! I'll follow up with the Google Fonts team If `ital`/`slnt` becomes an issue and see what works best for that axis.
