### ISSUE TITLE
Kerning adjustments: i + d (from Medium up)

### ISSUE THREAD

**Issue by erycsilva** [coreyhu/Urbanist#37]
Noticed some extra spacing between some letters from the Medium weight up to the Black weight.

### Screenshots Below

| [![QBm2W0.png](https://i.im.ge/2021/09/10/QBm2W0.png)](https://im.ge/i/QBm2W0) | [![QBmdoT.png](https://i.im.ge/2021/09/10/QBmdoT.png)](https://im.ge/i/QBmdoT) |

**Comment by coreyhu** [comment]
Hi, thanks for submitting an issue. This was due to a mistake with the spacing on the right side of the Black `i` (#33) and should be fixed in PR #34. [You can download the update in the latest release](https://github.com/coreyhu/Urbanist/releases/tag/v1.302). 

It may not be updated on Google Fonts for a while since changes there can take some time. I'll close this for now, but feel free to open another issue if you notice anything else. Thanks!
