### ISSUE TITLE
"i" has too much space if before or next to some letters.

### ISSUE THREAD

**Issue by ikx94** [coreyhu/Urbanist#38]
Hey, I just found this font on Google Fonts and I love it.

I've found that the i's have too much space when next to an a, v or e.

I attached some screenshots.

Not sure if it's intentional, but I think it would look better if it had a little less spacing after the i'
![firefox_f9OjaEbiOZ](https://user-images.githubusercontent.com/44823775/135529231-7c6afbab-2a00-455f-9c1f-4d2f6b33ccb0.png)
![firefox_e0fzUj11AZ](https://user-images.githubusercontent.com/44823775/135529237-a7f23b40-a6b4-40d4-9241-ffcf67866a41.png)
![firefox_8rfglObHbA](https://user-images.githubusercontent.com/44823775/135529239-a8f9296c-eb15-49d2-84f6-f051fc16635a.png)
![firefox_NmmJrIQ2SD](https://user-images.githubusercontent.com/44823775/135529242-b84a501c-f046-40cc-bb51-a32cb7c8342d.png)
![firefox_x7jR7cQEbG](https://user-images.githubusercontent.com/44823775/135529245-f3b27d46-481b-43c3-8b56-9b2788f8f75f.png)
![firefox_PZdlwSwERD](https://user-images.githubusercontent.com/44823775/135529247-739a9f97-cd48-4aae-8e7e-040480f81554.png)

Thank you for the great font.

**Comment by coreyhu** [comment]
Hi, thanks for filing this issue! Definitely not intentional and this was fixed in PR #34. [The fix is included in the latest release](https://github.com/coreyhu/Urbanist/releases/tag/v1.302). 

The version on Google Fonts may not be updated for some time unfortunately. Feel free to let me know if you spot any other issues!

**Comment by coreyhu** [comment]
Hi, thanks for filing this issue! Definitely not intentional and this was fixed in PR #34. [The fix is included in the latest release](https://github.com/coreyhu/Urbanist/releases/tag/v1.302). 

The version on Google Fonts may not be updated for some time unfortunately. Feel free to let me know if you spot any other issues!
